{% set name = "sendgrid" %}
{% set version = "6.7.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_value = "1c1cca97ab968f81af43ddbbe44aade5a689da27e3e4975dc366042499620abe" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - python_http_client >=3.2.1
    - pyyaml
    - ecdsa
    - six
    - starkbank-ecdsa >=1.0.0
    - werkzeug

test:
  imports:
    - sendgrid
    - sendgrid.helpers
    - sendgrid.helpers.inbound
    - sendgrid.helpers.mail
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sendgrid/sendgrid-python/
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: SendGrid library for Python
  description: "SendGrid Python library. This library allows you to quickly and easily use the SendGrid Web API v3 via Python"
  doc_url: 'https://github.com/sendgrid/sendgrid-python'
  dev_url: 'https://github.com/sendgrid/sendgrid-python'

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
