travis:
  secure:
    BINSTAR_TOKEN: p72yJiLwVhfefxBpyic/pPaC1pZeL/zHJP3onR+PrOZj9Zr3g1WokRRynjtUM9r2JqnUGfIWGNyIOFJMCTdurT9p22o70AeFoYRP5DIJgBjtiYdrU2gBazG1NhJ9GBUUJxemY720VlKmmQBOkmowfCV87tugVNVU0OZ1Ls+guFHUH+sijLf79YyztC33NHpOHH6QAf9WrJaCLJQQTzUBtqgQxzydHPFZOyTOn7YcMy9yOVZcVT3MJ4lWK6wEtPlCriKpMYiPPCBYie7l0KyfxDaGZ9hT9a4dYNqK9zh9Mj9dTZAwaUVta1TuEPJTKPa+tYcsHIo78Vhrg3Mz7w4FnCvt48xDWpr02HDevV9e5Sz2k1UTUjHgEshatgOSUU8tYmy5oZ+PIo+KhmgxhdhZXEd/T65YN8xf+4V2c+p9Vf6ep5jw+6uGv7F3FBmWI/sQEJgrUpxOObUbVVoTFGBCc/OBUTOAqqwRPHSjybvQqDz3oc9ENd2D9wFDlkHxisDpSS9SZFvGhh+a6D6kf/gkoqE+cp4eogN6Wjz2JdNNmhTM5mAOlvGeagPGMLFrKk/M31c0wjv5yc4fMWWREI8JcWk0MZudhcMmXleo5S1XG0TAzJE3bYEApelLNb1N1uJB4toB5vr1561lqH4PGk3p/UiTHgcowWE8CD+4j0FE8Ho=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
