travis:
  secure:
    BINSTAR_TOKEN: tVazhlQ5c/dZde3i6lHb3XTFr6VqtWIKDTQQGvf5ANJIm6ejx5hsPqMJqs+Qq/zTAM4LZVtHiE2LNMd4fAfQxn56aJ22zZUFAGAvO1kbXeFMOk6A54ik2hhGF77UkuuBZNY6CnZgPMh2Dsu/sqT7JYvYQYelRGKgAyDC/5PrsYZYKb9Vv6EtC6qvDyKU+gTCGj0yb6hNChIbIgNMBR33j3l/CLmXUAUytF1VM45UZ1pWts7h49JT5IK6d0ngJnJArKkjmwsJuWFl7wX3GUuhZeTq0Ol7AOfU1B778rhsG7Ub6+dF1sUoJqmV9xnYvVv2LwFyGX3rAWCKX4ZPv5L7+EL990Hlq4Vk72dsZk/6EOwH/MAYFt3Ly/sfUW1vj0p5jwPSSvE13WbMU4I8x1BrvUNIt9BB8XNUl+znaRXHJEOxfXgaCIF3Uebam8/JahOQjdMLTfrOODu5B7rZwayVlP/CPTx+9uIMMc1Mr1IErgzrWQTlhBmQGRWSCvxPVhj2rsvz3Nq2ZueCkENVZUgnrZPLxlwJl/7sckGeSVIbV28Hb/E43KnAs1uJ6lNVwrIOBgPUaiQp4xK+RnwMi9izSlYzlPXsQglA+i1qWZs1FT1cJRrPiTnhTBO6ZStieP0vaABfO12e1i7TDig80KyUXjz+YxUwK9kTHjctWjKuNqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
